const crypto = require('crypto')
const { publicKey, privateKey } = crypto.generateKeyPairSync('ec', { namedCurve: 'prime256v1' })
const pub = publicKey.export({ type: 'spki', format: 'der' })
const priv = privateKey.export({ type: 'pkcs8', format: 'der' })
const publicKeyBase64 = pub.slice(-65).toString('base64url')
const privateKeyBase64 = priv.slice(-32).toString('base64url')
console.log('=== VAPID KEYS ===')
console.log('Public Key: ' + publicKeyBase64)
console.log('Private Key: ' + privateKeyBase64)
